config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html



  resources :listings do
    resources :comments, only: %i[new create]

    member do
      patch 'accept_offer/:comment_id', to: 'listings#accept_offer', as: 'accept_offer'
    end
  end
  root to: "listings#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :listing
    belongs_to :user

    attribute :accepted, :boolean, default: false
end

app/models/comment_author.rb
class CommentAuthor < ApplicationRecord
    has_many :comments
    has_many :listings, through: :comments
    belongs_to :user
end

app/models/listing.rb
class Listing < ApplicationRecord

  has_many :comments, dependent: :destroy
  belongs_to :user, optional: true

    validates :title, presence: true
    validates :description, presence: true
    validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
    
    def self.title_search(string)
        Listing.where("title like ?", "%#{string}%")
    end

    def self.sorted_by(field)
      field = 'title' if field.nil? || !column_names.include?(field.to_s)
      order(field)
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :comment_author
  has_many :comments
  has_many :listings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

  def new
    # listing_id because of nested route
    @listing = Listing.find(params[:listing_id])
    @comment = Comment.new
  end

  def create
    # book_id because of nested route
    @listing = Listing.find(params[:listing_id])
     # build sets the book foreign key automatically
    @comment = @listing.comments.build(create_update_params)
    
    @comment.user = current_user
    
    if @comment.save
      flash[:notice] = 'Comment successfully created.'
      redirect_to(listing_path(@listing))
      
      
    else
      flash[:alert] = 'Failure to create new comment.'
      render :new, status: :unprocessable_entity
      # redirect_to(new_listing_comment_path(@listing))
    end
  end

  private
  def create_update_params
    params.require(:comment).permit(:commentText, :offer)
  end


end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
    searchfield = params[:title_search]
    @listings = if params[:title_search]
      Listing.title_search(searchfield)
    else
      Listing.all.order(params[:sort]) # order(title: :desc)
    end
    
  end

  def show
    @listing = Listing.find(params[:id])
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = current_user.listings.new(params.require(:listing).permit(:title, :description, :price, :date))
    if @listing.save
      flash[:notice] = "#{@listing.title} successfully posted"
      redirect_to listings_path and return
    else
      flash[:alert] = "Creation failed, invalid input"
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def update
    @listing = Listing.find(params[:id])
    if @listing.update(create_update_params)
      flash[:notice] = "#{@listing.title} successfully edited"
      redirect_to listing_path(@listing) and return
    else 
      flash[:alert] = "Edit Failed"
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
    flash[:alert] = "Listing #{@listing.title} deleted."
    redirect_to listings_path
  end

  def accept_offer
    @listing = Listing.find(params[:id])
    @comment = @listing.comments.find(params[:comment_id])
    @comment.update(accepted: true)
    @listing.destroy
    flash[:notice] = "Offer accepted. Listing sold!"
    redirect_to listings_path
  end

  private
  def create_update_params
    params.require(:listing).permit(:title, :price, :description, :date, :poster)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<tr>
  <td><%= comment.commentText %>
  <td><%= comment.offer %>
  <td><%= comment.user.email %>
</tr>

app/views/comments/new.html.erb
<%= form_with model: @comment, url: listing_comments_path(@listing), method: :post do |f| %>
    <div class="field">
      <%= f.label :commentText, "Comment" %>
      <%= f.text_field :commentText %>
    </div>
    <div class="field">
      <%= f.label :offer, "Offer" %>
      <%= f.number_field :offer %>
    </div>
    <br>
    <%= f.submit "Submit comment" %>
    <br>
  <% end %>
  
  <%= link_to 'Back to listing details', listing_path(@listing) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Swapshop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <p class="navbar-text float-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to "Edit profile", edit_user_registration_path, class: "navbar-link" %> |
      <%= link_to "Logout", destroy_user_session_path, data: { "turbo-method": :delete }, class: "navbar-link"  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, class: "navbar-link"  %> |
      <%= link_to "Login", new_user_session_path, class: "navbar-link"  %>
    <% end %>
  </p>

  <h1><%= link_to "SWAP-SHOP", listings_path, class: "title" %> </h1>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/listings/_form_template.html.erb
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@listing.errors.count, "error") %> prevented
        this listing from being saved:
      </h2>
      <ul>
        <% @listing.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= listing_form.label :title %>
  <%= listing_form.text_field :title %>
  <br>

  <%= listing_form.label :description %>
  <%= listing_form.text_field :description %>
  <br>

  <%= listing_form.label :price %>
  <%= listing_form.number_field :price, step: '0.01' %>
  <br>

  <%# listing_form.hidden_field :poster, value: current_user.username %>
  <%= listing_form.hidden_field :date, value: DateTime.now %>


  <%= listing_form.submit %>

app/views/listings/_listing.html.erb
<tr>
<td><%= link_to listing.title, listing_path(listing) %>
<td>  $<%= listing.price %>
<td><%= listing.description %>
<td><%= time_ago_in_words(listing.date) + " ago" %>
</tr>

app/views/listings/edit.html.erb
<div class="container">
<%# in app/views/books/edit.html.erb %>
<%= turbo_frame_tag "show_edit" do %>
    <%= form_with model: @listing, method: :put do |listing_form| %>
        
        <%= render partial: 'form_template', locals: {listing_form: listing_form} %>

    <% end %>
<%end%>
</div>

app/views/listings/index.html.erb
<section>

<div class="container">
  <div class="searchbox">
    <%= form_with url: listings_path, local: true, method: :get do %>
    <%= label_tag "title_search" %>
    <%= text_field_tag "title_search", nil, maxlength: 10 %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
    <%= link_to "Reset", listings_path, class: "btn btn-dark" %>
    <% end %> 
  </div>
  <br>

  <table class="table">
    <thead>
      <tr>
        <th><%= link_to 'Title', listings_path(sort: 'title'), class: 'index_header' %>
        <th><%= link_to 'Price', listings_path(sort: 'price'), class: 'index_header' %>
        <th class='index_header'>Description
        <th><%= link_to 'Date Posted', listings_path(sort: 'date'), class: 'index_header' %>
      </tr>
    </thead>
    <tbody>
      <%= render partial: 'listing', collection: @listings %>
    </tbody>
  </table>
  <br>
  <% if current_user %>
    <%= link_to "Post new listing", new_listing_path, class: "btn btn-secondary" %>
  <% else %>
    <%= link_to "Post new listing", "#", class: "btn btn-secondary disabled", disabled: true, onclick: "alert('Please sign in to post a new listing.')" %>
  <% end %>
  </div>
</section>

app/views/listings/new.html.erb
<div class="container">
<%# in app/views/listings/new.html.erb %>
<%= form_with model: @listing do |listing_form| %>

  <%= render partial: 'form_template', locals: {listing_form: listing_form} %>

<% end %>
</div>

app/views/listings/show.html.erb
<section id="main" class="container">

  <h1 class="product_title">Product details page: <%= @listing.title %></h1>
  <br>

  <%= turbo_frame_tag "show_edit" do %>
    <table class="table">
      <thead>
        <tr>
          <th> Title </th>
          <th> Description </th>
          <th> Posted By </th>
          <th> Date Posted </th>
          <th> Price </th>
        </tr>
      </thead>
      <tbody>
        <td><%= @listing.title %></td>
        <td><%= @listing.description %></td>
        <td><%= @listing.user&.email %></td>
        <td><%= time_ago_in_words(@listing.date) + " ago" %></td>
        <td><%= number_to_currency(@listing.price) %></td>
      </tbody>
    </table>
    <br>

    </dl>

    <% if current_user && (current_user == @listing.user || current_user.admin?) %>
      <%= link_to "Edit listing", edit_listing_path(@listing), class: "btn btn-info inline-button" %>
    <% end %>
  <%end%>
  <% if current_user && (current_user == @listing.user || current_user.admin?) %>
    <%= button_to "Delete listing", listing_path(@listing), method: :delete, form_class: "inline-button", class: "btn btn-danger" %>  <br>
  <% end %>
    
  <br>
  <br>

<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th>Comments</th>
        <th>Offer</th>
        <th>By</th>
        <% if current_user == @listing.user %>
          <th>Actions</th>
        <% end %>
      </tr>
    </thead>
    
    <tbody>
      <% @listing.comments.each do |comment| %>
    <tr>
      <td><%= comment.commentText %></td>
      <td>$<%= comment.offer %></td>
      <td><%= comment.user.email %></td>
      
      <% if current_user == @listing.user && !comment.accepted? %>
        <td>
        <%= button_to "Accept Offer", accept_offer_listing_path(@listing, comment), method: :patch, class: "btn btn-accept-offer" %>
        </td>
      <% end %>
      </td>
    </tr>
  <% end %>
    </tbody>

  </table>
</div>

<div>
<%if user_signed_in? %>
  <%= link_to "Write a new comment", new_listing_comment_path(@listing), class: "btn btn-secondary" %>
<% end %>
</div>
<br>

<%= link_to "Back to index", listings_path, class: "btn btn-primary" %>


</section>